name: Commit Message Check

on:
  push:
    # No branches specified - checks all branches

jobs:
  check-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate commit message with regex
        run: |
          git fetch --depth=1  # Fetch latest commits efficiently
          commit_messages=$(git log --pretty=format:%s HEAD~..HEAD)
          regex="^(feat|fix|docs): .*$"  # Replace with your desired regex pattern
          if [[ ! $(echo "$commit_messages" | grep -qE "$regex") ]]; then
            echo "Hey there! Looks like some commit messages don't follow our format "
            echo "**Quick reminder:** Please use a clear and concise message that starts with 'feat:', 'fix:', or 'docs:', followed by a brief description."
            echo "For example:"
            echo "```"
            echo "fix: Resolved the issue with the search bar"
            echo "```"
            echo "Let's keep those commit messages looking good! "
            exit 1  # Exit with non-zero code to indicate failure
          fi
