name: Greet on User First PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User on First PR Merge
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const authorLogin = context.payload.pull_request.user.login;

            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              author: authorLogin
            });

            if (pullRequests.length === 1) {
              const greetingMessage = `Congratulations, @${authorLogin} for your first pull request merge in this repository! 🎉🎉. Thanks for your contribution to JSON Schema!`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: greetingMessage
              });
            }
